# Generated by Django 5.2.15 on 2026-06-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postage_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('postage_class', models.IntegerField(choices=[(0, '2nd class'), (1, '1st class')], default=0)),
                ('parcel_size', models.IntegerField(choices=[(0, 'small'), (1, 'medium')], default=0)),
                ('max_weight', models.IntegerField(default=2, verbose_name='max weight in kg')),
                ('max_no_balls', models.IntegerField(default=50, verbose_name='max number of balls for parcel size')),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
