# Generated by Django 5.2.15 on 2026-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_postage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_buy', models.BooleanField(default=True)),
                ('lower_ball_num', models.IntegerField(blank=True, verbose_name='number of balls in small bulk buy')),
                ('lower_discount', models.IntegerField(blank=True, verbose_name='percentage discount for small bulk buy')),
                ('upper_ball_num', models.IntegerField(blank=True, verbose_name='number of balls for large bulk buy')),
                ('upper_discount', models.IntegerField(blank=True, verbose_name='percentage discount for large bulk buy')),
                ('active', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
