# Generated by Django 5.2.15 on 2026-06-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_percent', models.IntegerField(default=0, verbose_name='percentage discount for sale items')),
                ('active', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
