# Generated by Django 5.2.15 on 2026-06-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_email', models.EmailField(blank=True, max_length=254)),
                ('shop_phone', models.IntegerField(blank=True)),
                ('shop_street_address1', models.CharField(blank=True, max_length=80)),
                ('shop_street_address2', models.CharField(blank=True, max_length=80)),
                ('shop_town', models.CharField(blank=True, max_length=50)),
                ('shop_county', models.CharField(blank=True, max_length=40)),
                ('shop_country', models.CharField(default='GB')),
                ('shop_postcode', models.CharField(blank=True, max_length=9)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
