# Generated by Django 5.2.15 on 2026-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shopcontactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSlides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcements',
            options={'ordering': ['-updated_on'], 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='postage',
            options={'ordering': ['-updated_on'], 'verbose_name_plural': 'Postage'},
        ),
        migrations.AlterModelOptions(
            name='salesettings',
            options={'ordering': ['-updated_on'], 'verbose_name_plural': 'Sale Settings'},
        ),
        migrations.AlterModelOptions(
            name='shopcontactinfo',
            options={'ordering': ['-updated_on'], 'verbose_name_plural': 'Shop Contact Information'},
        ),
    ]
