# Generated by Django 5.2.15 on 2026-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepageslides_alter_announcements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslides',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepageslides',
            name='imageURL',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
