# Generated by Django 5.2.15 on 2026-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homepageslides_image_homepageslides_imageurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageslides',
            options={'ordering': ['updated_on'], 'verbose_name': 'Promotional images', 'verbose_name_plural': 'Promotional Images'},
        ),
        migrations.AddField(
            model_name='homepageslides',
            name='alt_text',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
