# Generated by Django 5.2.15 on 2026-07-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_homepageslides_options_homepageslides_alt_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageslides',
            options={'ordering': ['-updated_on'], 'verbose_name': 'Promotional images', 'verbose_name_plural': 'Promotional Images'},
        ),
    ]
