# Generated by Django 5.2.15 on 2026-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_homepageslides_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='temporary_basket',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
