# Generated by Django 5.2.15 on 2026-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_temporary_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wish_list',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
