# Generated by Django 5.2.15 on 2026-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprofile_default_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_phone',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
