# Generated by Django 5.2.15 on 2026-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_shopcontactinfo_shop_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postage',
            options={'ordering': ['postage_class'], 'verbose_name_plural': 'Postage'},
        ),
        migrations.AlterField(
            model_name='homepageslides',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postage',
            name='postage_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cost in £'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_country',
            field=models.CharField(default='GB', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_county',
            field=models.CharField(blank=True, max_length=40, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_phone',
            field=models.BigIntegerField(blank=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_postcode',
            field=models.CharField(blank=True, max_length=9, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_street_address1',
            field=models.CharField(blank=True, max_length=80, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_street_address2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='shopcontactinfo',
            name='shop_town',
            field=models.CharField(blank=True, max_length=50, verbose_name='Town'),
        ),
    ]
