# Generated by Django 5.2.15 on 2026-07-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('manufacturer_patterns', models.URLField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Colour_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=40, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shade_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('alt_names', models.CharField(blank=True, max_length=100, verbose_name='US terminology')),
            ],
            options={
                'verbose_name_plural': 'Thicknesses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price in £')),
                ('fibre', models.CharField(blank=True, max_length=500, null=True)),
                ('skein_weight', models.IntegerField(verbose_name='Weight of single ball in g')),
                ('skein_length', models.IntegerField(blank=True, null=True, verbose_name='Length of yarn in a single ball in m')),
                ('needle_size', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='recommended knitting needle size in mm')),
                ('knitting_tension', models.CharField(blank=True, max_length=300, null=True, verbose_name='st and row count to produce 10 x 10 cm square')),
                ('machine_wash', models.BooleanField(default=False)),
                ('wash_temp', models.IntegerField(blank=True, null=True, verbose_name='Washing Temperature in deg C')),
                ('tumble_dry', models.BooleanField(default=False)),
                ('dry_flat', models.BooleanField(default=False)),
                ('wool_cycle', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, max_length=500)),
                ('sku', models.CharField(max_length=5, unique=True)),
                ('visible', models.BooleanField(default=False)),
                ('on_promotion', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product.brand')),
                ('thickness_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thickness', to='product.thickness')),
            ],
        ),
        migrations.CreateModel(
            name='Colour_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade_code', models.IntegerField()),
                ('dye_lot', models.IntegerField()),
                ('low_stock', models.BooleanField(default=False)),
                ('colour_cat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colour', to='product.colour_cat')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='colour_cat',
            name='shade_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shade_type', to='product.shade_type'),
        ),
    ]
