# Generated by Django 5.2.15 on 2026-07-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_natural_fibres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='natural_fibres',
            field=models.BooleanField(default=False),
        ),
    ]
