# Generated by Django 5.2.15 on 2026-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour_var',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
