# Generated by Django 5.2.15 on 2026-08-27 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_colour_var_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colour_var',
            options={'ordering': ['product_id'], 'verbose_name': 'Yarn shade', 'verbose_name_plural': 'Yarn shades'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'brand_id', 'thickness_id']},
        ),
        migrations.AlterField(
            model_name='colour_cat',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='colour_var',
            name='colour_cat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colour', to='product.colour_cat', verbose_name='shade'),
        ),
        migrations.AlterField(
            model_name='colour_var',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='Yarn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product.brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='needle_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='recommended                                         knitting needle size in mm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thickness_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thickness', to='product.thickness', verbose_name='thickness'),
        ),
    ]
