# Generated by Django 5.2.15 on 2026-07-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_alter_userprofile_temporary_basket'),
        ('product', '0004_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('order_num', models.CharField(editable=False, max_length=8)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_street_address1', models.CharField(max_length=80)),
                ('billing_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('billing_town', models.CharField(max_length=50)),
                ('billing_county', models.CharField(max_length=40)),
                ('billing_postcode', models.CharField(max_length=9)),
                ('billing_country', models.CharField(default='GB', max_length=20)),
                ('shipping_street_address1', models.CharField(max_length=80)),
                ('shipping_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_town', models.CharField(max_length=50)),
                ('shipping_county', models.CharField(max_length=40)),
                ('shipping_postcode', models.CharField(max_length=9)),
                ('shipping_country', models.CharField(default='GB', editable=False, max_length=20)),
                ('basket_contents', models.TextField(default='')),
                ('is_gift', models.BooleanField(default=False)),
                ('gift_message', models.CharField(blank=True, max_length=500, null=True)),
                ('postage_class', models.IntegerField(choices=[(0, '2nd class'), (1, '1st class')], default=0)),
                ('parcel_size', models.IntegerField(choices=[(0, 'small'), (1, 'medium')])),
                ('order_subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('postage_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_shipped', models.BooleanField(default=False)),
                ('use_voucher', models.BooleanField(default=False)),
                ('voucher_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('amount_payable', models.DecimalField(decimal_places=2, max_digits=5)),
                ('refund_status', models.BooleanField(default=False)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='YarnOrderLineitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('linetotal', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('lineweight', models.IntegerField(editable=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('yarn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn', to='product.colour_var')),
            ],
        ),
    ]
