# Generated by Django 5.2.15 on 2026-07-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='GB', max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_county',
            field=models.CharField(max_length=40, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_postcode',
            field=models.CharField(max_length=9, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street_address1',
            field=models.CharField(help_text='Orders can only be shipped to UK addresses', max_length=80, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_town',
            field=models.CharField(max_length=50, verbose_name='Town or City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_gift',
            field=models.BooleanField(default=False, verbose_name='Order is a gift'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='parcel_size',
            field=models.IntegerField(choices=[(0, 'small'), (1, 'medium')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postage_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_county',
            field=models.CharField(max_length=40, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postcode',
            field=models.CharField(max_length=9, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street_address1',
            field=models.CharField(help_text='Orders can only be shipped to UK addresses', max_length=80, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street_address2',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Street Address 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_town',
            field=models.CharField(max_length=50, verbose_name='Town or City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='yarnorderlineitem',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
