# Generated by Django 5.2.15 on 2026-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_options_alter_order_amount_payable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
