# Generated by Django 5.2.15 on 2026-08-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_phone'),
        ('product', '0005_colour_var_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewYarns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='checkout.order')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn', to='product.product')),
            ],
        ),
    ]
