# Generated by Django 5.2.15 on 2026-08-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_created_on'),
        ('product', '0005_colour_var_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewyarns',
            name='yarn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_item', to='product.colour_var'),
        ),
    ]
