# Generated by Django 5.2.15 on 2026-08-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_reviewyarns_yarn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewyarns',
            options={'ordering': ['-updated_on'], 'verbose_name': 'reviews', 'verbose_name_plural': 'reviews'},
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refunded_order', to='checkout.order')),
            ],
        ),
        migrations.CreateModel(
            name='Shipped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched_on', models.DateTimeField(auto_now_add=True)),
                ('tracking_num', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipped', to='checkout.order')),
            ],
        ),
    ]
