# Generated by Django 5.2.15 on 2026-08-05 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_reviewyarns_options_refund_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
