# Generated by Django 5.2.15 on 2026-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_refund_refund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
