# Generated by Django 5.2.15 on 2026-08-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='shipped',
            options={'verbose_name_plural': 'Shipped'},
        ),
        migrations.RemoveField(
            model_name='shipped',
            name='tracking_num',
        ),
    ]
