# Generated by Django 5.2.15 on 2026-07-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.IntegerField(choices=[(0, 'A question about a product'), (1, 'A question about my order'), (2, 'Other')], default=2)),
                ('message', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Customer contact message',
                'verbose_name_plural': 'Customer contact messages',
                'ordering': ['-created_on'],
            },
        ),
    ]
